# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeHotkey.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import qdarkstyle
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeKeyWindow(object):
    def setupUi(self, ChangeKeyWindow):
        ChangeKeyWindow.setObjectName("ChangeKeyWindow")
        ChangeKeyWindow.resize(798, 600)
        ChangeKeyWindow.setMinimumSize(QtCore.QSize(300, 300))
        app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api='pyqt5'))
        self.centralwidget = QtWidgets.QWidget(ChangeKeyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.textLabel1.setGeometry(QtCore.QRect(100, 30, 611, 121))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.textLabel1.setFont(font)
        self.textLabel1.setObjectName("textLabel1")
        self.textLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.textLabel2.setGeometry(QtCore.QRect(170, 120, 661, 51))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.textLabel2.setFont(font)
        self.textLabel2.setObjectName("textLabel2")
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel.setGeometry(QtCore.QRect(290, 270, 221, 71))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(25)
        self.inputLabel.setFont(font)
        self.inputLabel.setText("")
        self.inputLabel.setObjectName("inputLabel")
        ChangeKeyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChangeKeyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 35))
        self.menubar.setObjectName("menubar")
        ChangeKeyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChangeKeyWindow)
        self.statusbar.setObjectName("statusbar")
        ChangeKeyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeKeyWindow)
        QtCore.QMetaObject.connectSlotsByName(ChangeKeyWindow)

    def retranslateUi(self, ChangeKeyWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangeKeyWindow.setWindowTitle(_translate("ChangeKeyWindow", "Change Hotkey"))
        self.textLabel1.setText(_translate("ChangeKeyWindow", "Start typing the new hotkey and it should "))
        self.textLabel2.setText(_translate("ChangeKeyWindow", "appear. Click enter to save it"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeKeyWindow = QtWidgets.QMainWindow()
    ui = Ui_ChangeKeyWindow()
    ui.setupUi(ChangeKeyWindow)
    ChangeKeyWindow.show()
    sys.exit(app.exec_())
